"""Post-process an OpenAPI 3.0 spec for Mintlify compatibility.

Fixes generated by nestjs-zod that are valid OpenAPI 3.1 but rejected
by Mintlify's stricter OpenAPI 3.0 validator:

  - Removes `propertyNames` (3.1 only)
  - Extracts inline object schemas with `properties` into top-level
    $ref definitions (Mintlify requires $ref for nested objects)
  - Converts numeric `exclusiveMinimum`/`exclusiveMaximum` (3.1) to
    the 3.0 boolean form

Usage:
    python3 scripts/prepare-openapi-for-mintlify.py docs/openapi.json
"""

import json
import sys


KEEP_TAGS = {"Agent API"}


def fix_spec(spec: dict) -> dict:
    # 1. Filter paths to only keep endpoints with the allowed tags.
    spec["paths"] = _filter_paths(spec.get("paths", {}))

    # 2. Fix schema compatibility issues.
    schemas = spec.get("components", {}).get("schemas", {})
    _fix_all_schemas(schemas)

    # 3. Remove unreferenced schemas to keep the spec clean.
    _prune_unused_schemas(spec)

    return spec


def _filter_paths(paths: dict) -> dict:
    """Keep only operations whose tags intersect with KEEP_TAGS."""
    filtered: dict = {}
    for path, methods in paths.items():
        kept_methods: dict = {}
        for method, operation in methods.items():
            if not isinstance(operation, dict):
                kept_methods[method] = operation
                continue
            tags = set(operation.get("tags", []))
            if tags & KEEP_TAGS:
                kept_methods[method] = operation
        if kept_methods:
            filtered[path] = kept_methods
    return filtered


def _collect_refs(obj, refs: set) -> None:
    """Recursively collect all $ref targets from the spec."""
    if isinstance(obj, dict):
        if "$ref" in obj:
            ref = obj["$ref"]
            if ref.startswith("#/components/schemas/"):
                refs.add(ref.split("/")[-1])
        for v in obj.values():
            _collect_refs(v, refs)
    elif isinstance(obj, list):
        for item in obj:
            _collect_refs(item, refs)


def _prune_unused_schemas(spec: dict) -> None:
    """Remove schemas not referenced (directly or transitively) by any path."""
    schemas = spec.get("components", {}).get("schemas", {})
    if not schemas:
        return

    # Collect refs from paths
    refs: set = set()
    _collect_refs(spec.get("paths", {}), refs)

    # Expand transitively: schemas can ref other schemas
    changed = True
    while changed:
        changed = False
        for name in list(refs):
            if name in schemas:
                new_refs: set = set()
                _collect_refs(schemas[name], new_refs)
                added = new_refs - refs
                if added:
                    refs |= added
                    changed = True

    # Remove unreferenced schemas
    for name in list(schemas.keys()):
        if name not in refs:
            del schemas[name]


def _fix_all_schemas(schemas: dict) -> None:
    # Run until no new schemas are added (extractions may create new ones).
    seen: set[str] = set()
    while True:
        pending = [n for n in schemas if n not in seen]
        if not pending:
            break
        for name in pending:
            seen.add(name)
            schema = schemas[name]
            props = schema.get("properties")
            if props and isinstance(props, dict):
                _fix_properties(props, name, schemas)


def _fix_properties(props: dict, prefix: str, schemas: dict) -> None:
    for key in list(props.keys()):
        prop = props[key]
        if not isinstance(prop, dict):
            continue

        # 1. Remove propertyNames (OpenAPI 3.1 only)
        prop.pop("propertyNames", None)

        # 2. Fix numeric exclusiveMinimum / exclusiveMaximum (3.1 → 3.0)
        for bound in ("exclusiveMinimum", "exclusiveMaximum"):
            val = prop.get(bound)
            if val is not None and isinstance(val, (int, float)) and not isinstance(val, bool):
                corresponding = "minimum" if "Min" in bound else "maximum"
                prop[corresponding] = prop.pop(bound)
                prop[bound] = True

        # 3. Extract inline objects with `properties` into $ref
        if (
            prop.get("type") == "object"
            and isinstance(prop.get("properties"), dict)
            and len(prop["properties"]) > 0
            and "$ref" not in prop
        ):
            ref_name = f"{prefix}{key[0].upper()}{key[1:]}"
            extracted = {"type": "object", "properties": prop["properties"]}
            if "required" in prop:
                extracted["required"] = prop["required"]
            if "additionalProperties" in prop:
                extracted["additionalProperties"] = prop["additionalProperties"]
            # Recursively fix the extracted schema's properties
            _fix_properties(extracted["properties"], ref_name, schemas)
            schemas[ref_name] = extracted
            nullable = prop.get("nullable")
            prop.clear()
            prop["$ref"] = f"#/components/schemas/{ref_name}"
            if nullable:
                prop["nullable"] = nullable

        # 4. Recurse into nested properties that weren't extracted
        if "properties" in prop and isinstance(prop["properties"], dict):
            child_prefix = f"{prefix}{key[0].upper()}{key[1:]}"
            _fix_properties(prop["properties"], child_prefix, schemas)


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python3 prepare-openapi-for-mintlify.py <openapi.json>")
        sys.exit(1)

    path = sys.argv[1]
    with open(path) as f:
        spec = json.load(f)

    spec = fix_spec(spec)

    with open(path, "w") as f:
        json.dump(spec, f, indent=4)
        f.write("\n")

    print(f"✅ OpenAPI spec fixed for Mintlify: {path}")


if __name__ == "__main__":
    main()
